import React from 'react';
import StarredHead from "@/app/components/ui/more/starred/StarredHead";

export const metadata = {
    title: 'WeTMS | Starred',
    description: 'Generated by Next.js',
}
const StarredPage = () => {
    return (
        <>
            <StarredHead />
        </>
    );
};

export default StarredPage;