import React from 'react';
import FavoriteHead from "@/app/components/ui/favorite/FavoriteHead";

export const metadata = {
    title: 'WeTMS | Favorites',
    description: 'Generated by Next.js',
}
const FavoritePage = () => {
    return (
        <>
          <FavoriteHead />
        </>
    );
};

export default FavoritePage;