import React from 'react';
import ProjectRectangleView from "@/app/components/ui/project/ProjectRectangleView";
import ProjectHead from "@/app/components/ui/project/ProjectHead";

export const metadata = {
    title: 'WeTMS | Projects',
    description: 'Generated by Next.js',
}
const ProjectPage = () => {

    return (
        <>
            <ProjectHead />
        </>
    );
};

export default ProjectPage;