"use client"
import React from 'react';
import {useCreateProjectStore} from "@/app/lib/store";
import CreateProjects from "@/app/components/ui/project/CreateProjects";
import ProjectRectangleView from "@/app/components/ui/project/ProjectRectangleView";
import PlusSvg from "@/app/components/icons/PlusSvg";
import ProjectHead from "@/app/components/ui/project/ProjectHead";

// export const metadata = {
//     title: 'WeTMS | Projects',
//     description: 'Generated by Next.js',
// }
const ProjectPage = () => {
    const {isOpen, setIsOpen, setUpdate, setUpdateData } = useCreateProjectStore();

    return (
        <>
            <div className="ks_w100 ks_d_flex ks_jt_cont_betw ks_alg_itm_ctr ks_brd_btm ks_pd_30">
                <label className="ks_fs22 ks_fw_bd ks_cs_pointer">
                    Projects
                </label>
                <button
                    className="btn btn-primary"
                        aria-expanded="false"
                        onClick={() => {
                            setIsOpen(true)
                        }}>
                        <PlusSvg />
                    Add Project
                </button>
            </div>

            <div className="ks_w100 ks_jt_cont_betw ks_alg_itm_ctr ks_brd_btm">
                <ProjectHead />

                <label className="ks_fs20 ks_fw_bd ks_cs_pointer ks_pl_30">
                    My Projects
                </label>
            </div>

            {/*<NoDataSave />*/}
            <ProjectRectangleView />

            {
                isOpen && <CreateProjects handleClose={() => setIsOpen(false)}/>
            }

        </>
    );
};

export default ProjectPage;