import { AuthLayout } from '@/app/components/layout'
import React, { PropsWithChildren } from 'react'

import "@/app/styles/ks_bootstrap.css"
import "@/app/styles/globals.css"
import "@/app/styles/we-tms.css"
import "bootstrap/dist/css/bootstrap.min.css";
import Sidebar from "@/app/components/layout/Sidebar";
import Navbar from "@/app/components/layout/Navbar";

export const metadata = {
    title: 'WeTMS | Home',
    description: 'Generated by Next.js',
}
const Layout = async ({ children }: PropsWithChildren) => {
  return (
      <html lang="en">
          <body>
          <AuthLayout>
              <div className="ks_d_flex ks_flex_col ks_flex_root">
                  <div className="ks_d_flex ks_flex_col ks_flex_col_fluid">
                      <Navbar/>
                      <div className="ks_d_flex ks_flex_col ks_flex_row_fluid" id="ks_wt_app_wrapper">
                          <Sidebar/>
                          {children}
                      </div>
                  </div>
              </div>
          </AuthLayout>
          </body>
      </html>
  )
}

export default Layout