import React from 'react';
import BookmarkHead from "@/app/components/ui/bookmark/BookmarkHead";

export const metadata = {
    title: 'WeTMS | Bookmarks',
    description: 'Generated by Next.js',
}
const BookmarkPage = () => {
    return (
        <>
           <BookmarkHead />
        </>
    );
};

export default BookmarkPage;