import { getServerSession } from 'next-auth';
import { redirect } from 'next/navigation';
import React from 'react'
import { authOption } from '@/lib/session/auth';
import LoginForm from '@/components/layout/LoginForm';



export const metadata = {
    title: 'WeTMS | Log In',
    description: 'Generated by Next.js',
}
const Login = async() => {

    const session = await getServerSession(authOption);

    if (session) {
        redirect("/login")
    }
    return <LoginForm/>;
    }

export default Login
