export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}
import "@/style/ks_bootstrap.css";
import "@/style/globals.css";
import "@/style/we-tms.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { AuthLayout } from "@/components/layout";


export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <AuthLayout>
                    {children}
                </AuthLayout>
            </body>
        </html>
    )
}
