import React from 'react';
import HiddenHead from "@/app/components/ui/more/hidden/HiddenHead";

export const metadata = {
    title: 'WeTMS | Hidden',
    description: 'Generated by Next.js',
}
const HiddenPage = () => {
    return (
        <>
           <HiddenHead />
        </>
    );
};

export default HiddenPage;