import React from 'react';
export const metadata = {
    title: 'WeTMS | Hidden',
    description: 'Generated by Next.js',
}
const HiddenPage = () => {
    return (
        <div>
            <div
                className="ks_w100 ks_d_flex ks_jt_cont_betw ks_alg_itm_ctr ks_plr300 ks_brd_btm ks_pt_30 ks_pr_20 ks_pb_30 ks_pl_20">
                <label className="ks_fs22 ks_fw_bd ks_cs_pointer">
                    Hidden
                </label>
            </div>
        </div>
    );
};

export default HiddenPage;